version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: flaskdb
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  app:
    build: .
    environment:
      FLASK_APP: app
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  dbdata: